MIN_REVIEWS_PER_USER = 5
SENTENCE_MODEL_NAME = "sentence-transformers/sentence-t5-xl"
SEQUENCE_LENGTH = 20
AMAZON_DS_YEAR = 2014

PADDING_VALUE = -1

USER_NUM_BINS = 2000
NUM_CODEBOOKS = 3
CODEBOOK_SIZE = 256

NUM_ENCODERS = 4
NUM_DECODERS = 4
NUM_HEADS = 6
HEAD_DIM = 64
FF_DIM = 1024
DROPOUT = 0.1
TOKEN_DIM = 128
