[tool.ruff]
line-length = 110
target-version = "py310"
exclude = ["scripts"]

[tool.ruff.lint]
select = [
    "A",   # flake8-builtins for errors when shadowing python builtins
    "B",   # flake8-bugbear for finding likely bugs and design problems
    "B9",  # flake8-bugbear for additional opinionated warnings
    "C4",  # flake8-comprehensions for writing better list/set/dict comprehensions
    "C90", # mccabe for cyclomatic complexity problems (see max-complexity below)
    "D",   # flake8-doctsrings. Checks for docstring conventions
    "E",   # pycodestyle check for pep8 style convention errors
    "F",   # flake8 error codes
    "I",   # import sorting
    "N",   # pep8-naming checks for naming conventions
    "S",   # flake8-bandit for finding common security issues
    "W",   # pycodestyle to check for pep8 style convention warnings
]

ignore = [
    "D1", # Missing docstrings
]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.per-file-ignores]
"**/test*.py" = ["S101"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.10"
strict_optional = false
ignore_missing_imports = true
exclude = "scripts"
